name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21', '1.22', '1.23' ]
    name: Go ${{ matrix.go }} tests
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
        
    - name: Install dependencies
      run: |
        go get -t -d -v ./...
        go get github.com/onsi/ginkgo/ginkgo
        go install github.com/onsi/ginkgo/ginkgo
        go get -u golang.org/x/lint/golint
        go get -u github.com/modocache/gover
        go install github.com/modocache/gover
        go get -u github.com/mattn/goveralls
        go install github.com/mattn/goveralls

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        working-directory: go/src/rn
        args: --timeout=20m -v
        skip-cache: false


    - name: Run tests
      run: |
        ginkgo -r -cover --randomizeAllSpecs --randomizeSuites --failOnPending --trace --race --progress
        ginkgo -tags=gorillamux -r --randomizeSuites --failOnPending --trace --race
        ginkgo -tags=gingonic -r --randomizeSuites --failOnPending --trace --race
        ginkgo -tags=echo -r --randomizeSuites --failOnPending --trace --race
        rm examples/examples.coverprofile
        bash scripts/fmtpolice
        gover
        goveralls -coverprofile=gover.coverprofile -repotoken gY90SprlNRGmSMl7MgybLreYa05wUXJTU
